name: Build and test Go
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/checkout@v2
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
          check-latest: true
        run: mkdir -p build/

      - name: Build for Windows amd64
				env:
					GOPROXY: "https://proxy.golang.org"
          GOARCH: "amd64"
          GOOS: "windows"
        run: go build -o build/win_amd64.exe cmds/patcher/main.go

      - name: Build for Mac amd64
				env:
					GOPROXY: "https://proxy.golang.org"
          GOARCH: "amd64"
          GOOS: "darwin"
        run: go build -o build/mac_amd64 cmds/patcher/main.go

      - name: Build for Mac arm64
				env:
					GOPROXY: "https://proxy.golang.org"
          GOARCH: "arm64"
          GOOS: "darwin"
        run: go build -o build/mac_arm64 cmds/patcher/main.go

      - name: Upload Windows amd64 build
        uses: actions/upload-artifact@v3
        with:
          name: windows-amd64
          path: build/win_amd64.exe

      - name: Upload Mac amd64 build
        uses: actions/upload-artifact@v3
        with:
          name: macos-amd64
          path: build/mac_amd64

      - name: Upload Mac arm64 build
        uses: actions/upload-artifact@v3
        with:
          name: macos-arm64
          path: build/mac_arm64